version: '3'

services:
  postgres:
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_USER: localuser
      POSTGRES_PASSWORD: localpass
      POSTGRES_DB: generatorgaza
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5201:5432'

volumes:
  pgdata:
